### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by maocheng2020** [arumugamlab/MIntO#15]
Hello, I want to ask what is going on with this error, I didn't find how to solve it, thank you!

snakemake --use-conda --restart-times 1 --keep-going --latency-wait 60 --jobs 32 --cores 64 --conda-prefix /home/pc/software/miniconda3/envs/MIntO --snakefile $MINTO_DIR/smk/dependencies.smk --configfile $MINTO_DIR/configuration/dependencies.yaml

Traceback (most recent call last):
  File "/home/pc/software/miniconda3/envs/MIntO/lib/python3.12/site-packages/snakemake/cli.py", line 1887, in args_to_api
    dag_api = workflow_api.dag(
              ^^^^^^^^^^^^^^^^^
  File "/home/pc/software/miniconda3/envs/MIntO/lib/python3.12/site-packages/snakemake/api.py", line 326, in dag
    return DAGApi(
           ^^^^^^^
  File "<string>", line 6, in __init__
  File "/home/pc/software/miniconda3/envs/MIntO/lib/python3.12/site-packages/snakemake/api.py", line 421, in __post_init__
    self.workflow_api._workflow.dag_settings = self.dag_settings
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pc/software/miniconda3/envs/MIntO/lib/python3.12/site-packages/snakemake/api.py", line 372, in _workflow
    workflow.include(
  File "/home/pc/software/miniconda3/envs/MIntO/lib/python3.12/site-packages/snakemake/workflow.py", line 1369, in include
    exec(compile(code, snakefile.get_path_or_uri(), "exec"), self.globals)
  File "/root/data/APP_MIntO/MIntO/smk/dependencies.smk", line 15, in <module>
    include: 'include/cmdline_validator.smk'
  File "/home/pc/software/miniconda3/envs/MIntO/lib/python3.12/site-packages/snakemake/workflow.py", line 1369, in include
    exec(compile(code, snakefile.get_path_or_uri(), "exec"), self.globals)
  File "/root/data/APP_MIntO/MIntO/smk/include/cmdline_validator.smk", line 11, in <module>
    if workflow.shadow_prefix is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Workflow' object has no attribute 'shadow_prefix'

**Comment by maocheng2020** [comment]
> Hi, Thanks for reporting this. Could you please tell us which version of `Snakemake` you are using?
> 
> A tip: The location for `--conda-prefix` should not be confused with your system `conda` installation or environment location. This is just a folder where `Snakemake` will organize all environments on behalf of MIntO. We recommend that you **do not** use the system directories here. This may not cause any problems, but ideally you do not want to mess with system directories. Our recommendation is to use `--conda-prefix $MINTO_DIR/conda_env`.

Thanks for your response, snakemake version is 8.1.0, I'll replace my original code with "--conda-prefix $MINTO_DIR/conda_env", I'm not familiar with snakemake, I still haven't been able to solve the problem that came up before.

**Comment by microbiomix** [comment]
Hi, Sorry for the delayed response.

MIntO expects `Snakemake` to be version `7.x.x`. The latest version `7.32.4` works fine. `Snakemake` interfaces changes dramatically from `8.0.0`, so MIntO is not compatible with that anymore.

We have now updated the installation instructions on how to specifically install `Snakemake` version `7` and also python `v3.11` to ensure compatibility with MIntO. Please wipe your current installation and start fresh, and get MIntO stable release `2.0.0`. If you run into any trouble, please do let us know.

P.S. The `--conda-prefix` suggestion was not connected to this bug. It was just a general suggestion.

**Comment by microbiomix** [comment]
Closing as there was no feedback or follow up. Please reopen if it continues to be an issue.
